#!/usr/bin/env bash
#Script displays Best School 10 times, but for the 9th line it has a hi

a=0
while [ $a -le 9 ];
do
	if [ $a == 8 ]; then
		echo "Hi"
		a=$((a+1))
	else
		echo "Best School"
		a=$((a+1))
	fi
done
