#!/usr/bin/env bash
#script creates a file containing its PID 
#displays infinity and beyond indefinitely
#diplays a text when receiving a SIGTERM and SIGINT signal
#terminates when it rereceives a SIGTERM or SITERM signal
terminator(){
	rm /var/run/myscript.pid
	exit
}
echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'terminator' SIGQUIT 
done
