#!/usr/bin/bash
#script creates a file containing its PID 
#displays infinity and beyond indefinitely
#diplays a text when receiving a SIGTERM and SIGINT signal
#terminates when it rereceives a SIGTERM or SITERM signal


