#!/usr/bin/env bash
#script displays infinity statement indefinitely with iterations and killed

trap 'echo "I am invincible!!!"; exit 0' SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done	
